# Generated by Django 3.0.6 on 2023-06-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBudget', models.DateField(db_column='DateBudget')),
                ('depense', models.IntegerField(blank=True, db_column='Depense', null=True)),
                ('recette', models.IntegerField(blank=True, db_column='Recette', null=True)),
                ('creepar', models.CharField(blank=True, db_column='CreateurEtat', max_length=100, null=True, verbose_name="Createur de Budget journalier'")),
                ('modifierpar', models.CharField(blank=True, db_column='QuiModifEtat', max_length=100, null=True, verbose_name='Modificateur de Budget journalier')),
            ],
            options={
                'verbose_name': 'Budget Journalier',
            },
        ),
    ]
