# Generated by Django 3.2.19 on 2023-07-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codearticle', models.CharField(blank=True, db_column='CodeArticle', max_length=250, null=True, verbose_name='Code Article')),
                ('nomarticle', models.CharField(blank=True, db_column='LibelleArticle', max_length=250, null=True, verbose_name='Libellé Article')),
                ('prixunitaire', models.IntegerField(blank=True, db_column='PrixUnitaire', null=True, verbose_name='Prix Unitaire')),
                ('designation', models.TextField(blank=True, db_column='Designation', null=True)),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
        migrations.CreateModel(
            name='BudgetJournalier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejournee', models.DateField(db_column='DateJournee', verbose_name='Date de la journee')),
                ('depenseglobal', models.IntegerField(blank=True, db_column='Depense', null=True)),
                ('recetteglobal', models.IntegerField(blank=True, db_column='Recette', null=True)),
                ('reamrque', models.TextField(blank=True, db_column='Remarque', null=True)),
                ('creepar', models.CharField(blank=True, db_column='CreateurEtat', max_length=100, null=True, verbose_name="Createur de Budget journalier'")),
                ('modifierpar', models.CharField(blank=True, db_column='QuiModifEtat', max_length=100, null=True, verbose_name='Modificateur de Budget journalier')),
            ],
            options={
                'verbose_name': 'Budget Journalier',
            },
        ),
        migrations.CreateModel(
            name='Fournissuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numfournisseur', models.IntegerField(blank=True, db_column='NumFournisseur', null=True, verbose_name='Numéro fournisseur')),
                ('nomfournisseur', models.CharField(blank=True, db_column='NomFournisseur', max_length=250, null=True, verbose_name='Nom Fournissuer')),
                ('addressfournisseur', models.TextField(blank=True, db_column='AddressFournisseur', max_length=250, null=True, verbose_name='Adress de Fournisseur')),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refmagasin', models.CharField(blank=True, db_column='RefMagasin', max_length=250, null=True, verbose_name='Référence Magasin Article')),
                ('libmagasin', models.CharField(blank=True, db_column='LibelleMagasin', max_length=250, null=True, verbose_name='Libellé Magasin')),
                ('lieumagasin', models.TextField(blank=True, db_column='LieuMagasin', max_length=250, null=True, verbose_name='Lieu Magasin')),
            ],
            options={
                'verbose_name': 'Magasin',
            },
        ),
        migrations.CreateModel(
            name='StockGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteglobalstock', models.IntegerField(blank=True, db_column='QteGlobalStock', null=True)),
                ('libellestockglobal', models.CharField(blank=True, db_column='LibelleStkG', max_length=250, null=True, verbose_name='Libelle de Stock Global')),
                ('article', models.ForeignKey(blank=True, db_column='ArticleInStock', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
    ]
