# Generated by Django 3.2.19 on 2023-07-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeStockGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateentree', models.DateField(blank=True, db_column='DateEntreeStck', null=True, verbose_name='Date Entree Au Stock')),
                ('quantiteentree', models.IntegerField(blank=True, db_column='QteEntred', null=True, verbose_name='Quantite Entree Au Stock')),
                ('id_stockglobal', models.ForeignKey(blank=True, db_column='StockGlobalArticle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_stocks', to='core.stockglobal')),
                ('idfournisseur', models.ForeignKey(blank=True, db_column='FournisseurArticle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_fournisseurs', to='core.fournissuer', verbose_name='Fournisseur article')),
            ],
            options={
                'verbose_name': 'Entree Au Stock',
                'db_table': 'Entree_Stock_Global',
            },
        ),
    ]
