# Generated by Django 3.0.6 on 2023-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='reamrque',
            field=models.TextField(blank=True, db_column='Remarque', null=True),
        ),
    ]
