# Generated by Django 3.0.6 on 2023-07-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230711_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreestockglobal',
            old_name='id_stockmagasin',
            new_name='id_stockglobal',
        ),
    ]
