# Generated by Django 3.0.6 on 2023-07-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230711_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreestockmagasin',
            name='montantarticle',
            field=models.IntegerField(blank=True, db_column='MontantArtcile', null=True, verbose_name='Montant Par Article'),
        ),
    ]
