# Generated by Django 3.0.6 on 2023-07-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entreestockmagasin_montantarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreestockmagasin',
            name='montantarticle',
        ),
    ]
