# Generated by Django 3.0.6 on 2023-07-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_entreestockmagasin_montantarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetjournalier',
            name='depenseglobal',
            field=models.FloatField(blank=True, db_column='Depense', null=True),
        ),
        migrations.AlterField(
            model_name='budgetjournalier',
            name='recetteglobal',
            field=models.FloatField(blank=True, db_column='Recette', null=True),
        ),
        migrations.AlterField(
            model_name='depensemagasinjr',
            name='montantdepense',
            field=models.FloatField(blank=True, db_column='MontantDepense', null=True, verbose_name='Montant de depenses'),
        ),
        migrations.AlterField(
            model_name='recettemagasinjr',
            name='montantrecette',
            field=models.FloatField(blank=True, db_column='MontantArticle', null=True, verbose_name='Montant de recette par article'),
        ),
    ]
