# Generated by Django 3.0.6 on 2023-07-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230715_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depensemagasinjr',
            old_name='id_budgetj',
            new_name='id_budgetjr',
        ),
    ]
