# Generated by Django 3.2.19 on 2023-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230715_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmagasin',
            name='prixvente',
            field=models.IntegerField(blank=True, db_column='PrixVente', null=True, verbose_name='Prix de vente'),
        ),
    ]
